pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sanjishiva5/jenkins-demo:latest"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'ci-cd-jenkins-20250217-015256', url: 'https://github.com/shivam5555/Devops-Clouds.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} ."
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh "docker push ${DOCKER_IMAGE}"
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                sh "docker-compose up -d"
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully!"
        }
        failure {
            echo "Pipeline failed. Check logs."
        }
    }
}

