pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sanjishiva5/flask-calculator"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'ci-cd-jenkins-docker-python', url: 'https://github.com/shivam5555/Devops-Clouds.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} ."
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh "docker push ${DOCKER_IMAGE}"
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh """
                docker stop flask-calculator || true
                docker rm flask-calculator || true
                docker pull ${DOCKER_IMAGE}
                docker run -d -p 5000:5000 --name flask-calculator ${DOCKER_IMAGE}
                """
            }
        }
    }

    post {
        success {
            echo "✅ Deployment Successful!"
        }
        failure {
            echo "❌ Deployment Failed! Check logs."
        }
    }
}

