pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sanjishiva5/flask-calculator"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'ci-cd-jenkins-docker-python', url: 'https://github.com/shivam5555/Devops-clouds.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} ."
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: 'https://hub.docker.com/repositories/sanjishiva5') {
                    sh "docker push ${DOCKER_IMAGE}"
                }
            }
        }

        stage('Deploy Container') {
            steps {
		script {
            sh """
            echo "🔄 Stopping any existing container..."
            docker stop flask-calculator || true
            docker rm flask-calculator || true

            echo "📥 Pulling the latest image..."
            docker pull ${DOCKER_IMAGE}

            echo "🚀 Running Flask Calculator container..."
            docker run -d -p 5000:5000 --name flask-calculator ${DOCKER_IMAGE}

            echo "✅ Deployment Complete. Checking running containers..."
            docker ps
            """
               
            }
        }
    }

    post {
        success {
            echo "✅ Deployment Successful!"
        }
        failure {
            echo "❌ Deployment Failed! Check logs."
        }
    }
}

