pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'ci-cd-jenkins-docker-python', url: 'https://github.com/shivam5555/Devops-Clouds.git'
            }
        }

        stage('Build') {
            steps {
                sh #!/bin/bash 'echo Building the application shivam ..."'
            }
        }

        stage('Test') {
            steps {
                sh #!/bin/bash 'echo "Running tests..."'
            }
        }

        stage('Deploy') {
            steps {
                sh #!/bin/bash 'echo "Deploying application..."'
            }
        }
    }
}

