name: CI Workflow

on:
  push:
    branches:
      - ci-cd-github-actions
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Success Message
        run: echo "✅ GitHub Actions is running successfully!"

